_commit: v1.12.1-10-g6796849
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Media Requester
homepageEnabled: true
homepageGroup: media
homepageIcon: jellyseerr
homepageName: Jellyseerr
ingClass: nginx-external
ingCname: crt.lol
ingExtraAnnotations: ''
ingHost: trl.crt.lol
ingName: jellyseerr
ingPathType: Prefix
ingWebSockets: false
ingress: true
labels: 'app: jellyseerr'
name: jellyseerr
namespace: jellyseerr
pvc: true
pvcAccessMode: ReadWriteOnce
pvcName: jellyseerr
pvcSize: 5Gi
pvcStorageClass: longhorn-retain
reloader: true
resources:
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
svcName: jellyseerr
svcPortNum: 5055
upstreamURL: https://jellyseerr.dev
url: https://github.com/charlesthomas/homelab-jellyseerr
