---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyseerr

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyseerr
commonLabels:
  app: jellyseerr

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml
- resources/statefulsets.yaml

images:
  - name: postgres
    newTag: 17-alpine
  - name: jellyseerr
    newName: fallenbagel/jellyseerr
    newTag: 2.5.2

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: jellyseerr
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: all
      namespace: jellyseerr
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: StatefulSet
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: jellyseerr
      namespace: jellyseerr
      annotations:
        gethomepage.dev/href: https://trl.crt.lol
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Media Requester
        gethomepage.dev/group: media
        gethomepage.dev/icon: jellyseerr
        gethomepage.dev/name: Jellyseerr
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
