---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyseer

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyseer
commonLabels:
  app: jellyseer

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml
- resources/statefulsets.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: jellyseer
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: all
      namespace: jellyseer
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: StatefulSet
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: jellyseer
      namespace: jellyseer
      annotations:
        gethomepage.dev/href: https://trl.crt.lol
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Media Requester
        gethomepage.dev/group: media
        gethomepage.dev/icon: jellyseer
        gethomepage.dev/name: Jellyseer
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
