---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jellyseerr
  namespace: jellyseerr
  labels:
    app: jellyseerr
spec:
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      dnsConfig:
        nameservers:
        - 10.43.0.10
      dnsPolicy: None
      containers:
      - name: jellyseerr
        image: jellyseerr
        imagePullPolicy: IfNotPresent
        ports:
        - name: jellyseerr
          containerPort: 5055
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres
              key: password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: username
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres.jellyseerr.svc.cluster.local
        - name: DB_NAME
          value: jellyseerr
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Detroit"
        - name: UMASK
          value: "022"
        volumeMounts:
        - name: jellyseerr
          mountPath: /app/config
        resources:
          limits:
            memory: 4Gi
        readinessProbe:
          tcpSocket:
            port: jellyseerr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: jellyseerr
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: jellyseerr
        persistentVolumeClaim:
          claimName: jellyseerr
