---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
